-- KEYS[1] = voucher stock key
-- KEYS[2] = user order key
-- ARGV[1] = userId
-- ARGV[2] = orderId
local stock = tonumber(redis.call('get', KEYS[1]))
if stock <= 0 then
    return 0
end
if redis.call('sismember', KEYS[2], ARGV[1]) == 1 then
    return 2
end
redis.call('decr', KEYS[1])
redis.call('sadd', KEYS[2], ARGV[1])
return 1---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by LEGION.
--- DateTime: 2026/3/8 14:36
---